Replace build-test and run_tests with a single script

diff --git a/git_hooks/pre-commit b/git_hooks/pre-commit
--- a/git_hooks/pre-commit
+++ b/git_hooks/pre-commit
@@ -4,21 +4,21 @@
 
 LISP="sbcl --noinform --no-userinit"
 topdir=$(git rev-parse --show-toplevel)
-run_build_test=false
+run_test_suite=false
 
 cd "$topdir"
 for x in $(git diff-index --cached --name-only HEAD) ; do
     case "$x" in
         scripts/*) continue ;;
-        *.lisp|*.asd) run_build_test=true ;;
+        *.lisp|*.asd) run_test_suite=true ;;
     esac
 done
 
-if $run_build_test ; then
-    echo "Running build test" >&2
-    $LISP --load scripts/buildtest.lisp --eval '(buildtest :cl-webkit2)' >&2
+if $run_test_suite ; then
+    echo "Running test-suite" >&2
+    $LISP --load scripts/run-tests.lisp >&2
     if [ $? -ne 0 ] ; then
-        echo "Commit rejected: build failed" >&2
+        echo "Commit rejected: test-suite failed" >&2
         exit 1
     fi
 fi
